version: '3'

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile.front
    ports:
      - "0.0.0.0:80:3000"

  back:
    build:
      context: ./
      dockerfile: Dockerfile.back
    ports:
      - "0.0.0.0:3001:3001"